version: "3.5"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - islanders-mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=islanders
    ports:
      - 27017:27017

  islanders-server:
    image: islanders/islanders-server:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongo
    links:
      - mongo

  islanders-client:
    image: islanders/islanders-client:latest
    restart: unless-stopped
    ports:
      - 80:80


volumes:
  islanders-mongo-data:
