version: '3.5'
services:
  pilgrims-client:
    image: pilgrims/pilgrims-client:latest
    container_name: pilgrims-client
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.backend=pilgrims-client"
      - "traefik.frontend.rule=Host:pilgrims.localhost"
    networks:
      - traefik_proxy
  
  pilgrims-server:
    image: pilgrims/pilgrims-server:latest
    container_name: pilgrims-server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.backend=pilgrims-server"
      - "traefik.frontend.rule=Host:pilgrims.localhost;PathPrefix:/api/"
    networks:
      - traefik_proxy


networks:
  traefik_proxy:
    external: true
