version: "3.5"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - pilgrims-mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pilgrims
    ports:
      - 27017:27017

  pilgrims-server:
    image: pilgrims/pilgrims-server:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongo
    links:
      - mongo

  pilgrims-client:
    image: pilgrims/pilgrims-client:latest
    restart: unless-stopped
    ports:
      - 80:80


volumes:
  pilgrims-mongo-data:
