version: "3.5"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - colonists-mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=colonists
    ports:
      - 27017:27017

  colonists-server:
    image: colonists/colonists-server:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongo
    links:
      - mongo

  colonists-client:
    image: colonists/colonists-client:latest
    restart: unless-stopped
    ports:
      - 80:80


volumes:
  colonists-mongo-data:
